name: Build and deploy

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/workflows/dependabot.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Kjøre tester i testapp
        run: |
          ./mvnw install
          cd dusseldorf-ktor-testapp
          ./gradlew test
