name: Pull request

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/workflows/dependabot.yml'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Kjøre tester i testapp
        run: |
          ./mvnw install
          cd dusseldorf-ktor-testapp
          ./gradlew test
